"use client"

import { motion } from "framer-motion"
import { Bot, FileText, Brain, MessageSquare } from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export default function AIFeatureSection() {
  return (
    <section className="py-16">
      <div className="container mx-auto px-4 md:px-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5 }}
            viewport={{ once: true }}
            className="space-y-4"
          >
            <div className="inline-block rounded-lg bg-primary/10 px-3 py-1 text-sm">Powered by AI</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl gradient-text">
              AI-Powered Features
            </h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed">
              Our platform leverages cutting-edge AI technology to provide personalized assistance and insights for
              students and companies.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" className="gap-1">
                Try AI Features <Bot className="h-4 w-4" />
              </Button>
              <Button size="lg" variant="outline" className="gap-1">
                Learn More
              </Button>
            </div>
          </motion.div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              viewport={{ once: true }}
            >
              <Card className="h-full">
                <CardHeader className="pb-2">
                  <div className="p-2 rounded-full bg-blue-500/10 w-fit">
                    <FileText className="h-5 w-5 text-blue-500" />
                  </div>
                  <CardTitle className="mt-2">Resume Analyzer</CardTitle>
                  <CardDescription>AI-powered resume analysis with personalized feedback</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Our AI analyzes your resume, identifies strengths and weaknesses, and provides actionable
                    suggestions for improvement.
                  </p>
                </CardContent>
              </Card>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              viewport={{ once: true }}
            >
              <Card className="h-full">
                <CardHeader className="pb-2">
                  <div className="p-2 rounded-full bg-green-500/10 w-fit">
                    <Brain className="h-5 w-5 text-green-500" />
                  </div>
                  <CardTitle className="mt-2">Roadmap Generator</CardTitle>
                  <CardDescription>Personalized career roadmaps based on your goals</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Get a customized learning and career roadmap generated by AI based on your skills, interests, and
                    career goals.
                  </p>
                </CardContent>
              </Card>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              viewport={{ once: true }}
            >
              <Card className="h-full">
                <CardHeader className="pb-2">
                  <div className="p-2 rounded-full bg-purple-500/10 w-fit">
                    <MessageSquare className="h-5 w-5 text-purple-500" />
                  </div>
                  <CardTitle className="mt-2">Interview Chatbot</CardTitle>
                  <CardDescription>Practice interviews with our AI assistant</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Prepare for interviews with our AI chatbot that simulates real interview scenarios and provides
                    feedback on your responses.
                  </p>
                </CardContent>
              </Card>
            </motion.div>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.4 }}
              viewport={{ once: true }}
            >
              <Card className="h-full">
                <CardHeader className="pb-2">
                  <div className="p-2 rounded-full bg-amber-500/10 w-fit">
                    <Bot className="h-5 w-5 text-amber-500" />
                  </div>
                  <CardTitle className="mt-2">Candidate Matching</CardTitle>
                  <CardDescription>AI-powered matching for companies and candidates</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Our AI algorithm matches companies with the most suitable candidates based on skills, experience,
                    and job requirements.
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          </div>
        </div>
      </div>

      <div className="section-divider mt-16"></div>
    </section>
  )
}

