# Generated by Django 5.0.2 on 2025-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=200)),
                ('current_skills', models.JSONField(default=list)),
                ('target_skills', models.JSONField(default=list)),
                ('learning_path', models.JSONField(default=list)),
                ('recommended_courses', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('milestones', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('behavioral', 'Behavioral'), ('system_design', 'System Design')], max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('common_questions', models.JSONField(default=list)),
                ('sample_answers', models.JSONField(default=dict)),
                ('tips', models.TextField()),
                ('resources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resume_analyses/')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('skills_match', models.JSONField(default=dict)),
                ('improvement_suggestions', models.TextField()),
                ('overall_score', models.IntegerField()),
                ('keywords_found', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
            ],
        ),
    ]
