# Generated by Django 5.0.2 on 2025-03-19 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerroadmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preparations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
