# Generated by Django 5.0.2 on 2025-03-19 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_initial'),
        ('jobs', '0003_company_jobcategory_rename_job_type_job_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewpreparation',
            old_name='last_accessed',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='analysis_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='resume_file',
            new_name='resume',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='current_skills',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='learning_path',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='milestones',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='recommended_courses',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='skill_gaps',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='target_role',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='target_skills',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='common_questions',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='interview_type',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='sample_answers',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='tips',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='improvement_suggestions',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='keywords_found',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='missing_keywords',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='overall_score',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='skills_match',
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='roadmap_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_preparations', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='preparation_content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
