# Generated by Django 5.0.2 on 2025-03-19 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0003_rename_last_accessed_interviewpreparation_updated_at_and_more'),
        ('jobs', '0004_alter_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/ats_reviews/')),
                ('ats_score', models.FloatField()),
                ('matched_keywords', models.JSONField()),
                ('missing_keywords', models.JSONField()),
                ('format_analysis', models.JSONField()),
                ('section_completeness', models.JSONField()),
                ('optimization_tips', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_reviews', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ATS Review',
                'verbose_name_plural': 'ATS Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
