# Generated by Django 4.2.10 on 2025-03-20 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_services', '0004_atsreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerroadmap',
            options={'ordering': ['-created_at'], 'verbose_name': 'Career Roadmap', 'verbose_name_plural': 'Career Roadmaps'},
        ),
        migrations.AlterModelOptions(
            name='interviewpreparation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interview Preparation', 'verbose_name_plural': 'Interview Preparations'},
        ),
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resume Analysis', 'verbose_name_plural': 'Resume Analyses'},
        ),
        migrations.RenameField(
            model_name='atsreview',
            old_name='format_analysis',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='atsreview',
            name='ats_score',
        ),
        migrations.RemoveField(
            model_name='atsreview',
            name='job',
        ),
        migrations.RemoveField(
            model_name='atsreview',
            name='matched_keywords',
        ),
        migrations.RemoveField(
            model_name='atsreview',
            name='missing_keywords',
        ),
        migrations.RemoveField(
            model_name='atsreview',
            name='optimization_tips',
        ),
        migrations.RemoveField(
            model_name='atsreview',
            name='section_completeness',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='status',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='interviewpreparation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='analysis_result',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='job',
        ),
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='status',
        ),
        migrations.AddField(
            model_name='atsreview',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='career_goals',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='milestones',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='preferences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='skills_to_acquire',
            field=models.JSONField(default='Career progression and skill development'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerroadmap',
            name='timeline',
            field=models.JSONField(default='Career progression and skill development'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='behavioral_questions',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='common_questions',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='company',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='job_title',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='technical_questions',
            field=models.JSONField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewpreparation',
            name='tips',
            field=models.JSONField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis',
            field=models.JSONField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='atsreview',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='atsreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='careerroadmap',
            name='roadmap_content',
            field=models.JSONField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careerroadmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewpreparation',
            name='preparation_content',
            field=models.JSONField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interviewpreparation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
