# Generated by Django 4.2.10 on 2025-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0005_alter_careerroadmap_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atsreview',
            old_name='review',
            new_name='analysis',
        ),
        migrations.AddField(
            model_name='atsreview',
            name='job_description',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
    ]
